# Generated by Django 5.0 on 2024-02-03 21:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_name', models.CharField(max_length=255)),
                ('dep_name', models.CharField(default='Inconnu', max_length=255)),
                ('com_name', models.CharField(default='Inconnu', max_length=255)),
                ('com_code', models.CharField(default='Inconnu', max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'georef_france_commune',
            },
        ),
        migrations.CreateModel(
            name='Hopitaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amenity', models.CharField(max_length=255)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'hopitaux',
            },
        ),
    ]
